# Generated by Django 6.0.5 on 2026-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('apk_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'APK Link',
                'verbose_name_plural': 'APK Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Channel Link',
                'verbose_name_plural': 'Channel Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_link', models.URLField(blank=True, default='https://t.me/', max_length=500)),
                ('youtube_link', models.URLField(blank=True, default='https://youtube.com/', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Links',
                'verbose_name_plural': 'Site Links',
            },
        ),
        migrations.CreateModel(
            name='WorkMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='work_methods/')),
                ('video_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Method',
                'verbose_name_plural': 'Work Methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
