# Generated by Django 6.0.5 on 2026-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alllinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Telegram, YouTube, Instagram', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('icon_class', models.CharField(default='fas fa-link', help_text='Font Awesome 6 icon class, e.g. fab fa-telegram, fab fa-youtube', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
