# Generated by Django 6.0.5 on 2026-05-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alllinks', '0002_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRequiredConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_link', models.URLField(blank=True, default='https://t.me/', max_length=500)),
            ],
            options={
                'verbose_name': 'Telegram Required Config',
                'verbose_name_plural': 'Telegram Required Config',
            },
        ),
    ]
