# Generated by Django 6.0.5 on 2026-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alllinks', '0003_telegramrequiredconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(default='fas fa-users', help_text='Font Awesome 6 icon class, e.g. fas fa-users, fas fa-info-circle', max_length=100)),
            ],
            options={
                'verbose_name': 'About Us Config',
                'verbose_name_plural': 'About Us Config',
            },
        ),
    ]
