# Generated by Django 6.0.5 on 2026-05-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alllinks', '0004_aboutusconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLinks',
        ),
    ]
