# Generated by Django 6.0.5 on 2026-05-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alllinks', '0005_delete_sitelinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmethod',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='workmethod',
            name='thumbnail_telegram_file_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
