# Generated by Django 6.0.5 on 2026-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alllinks', '0006_remove_workmethod_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channellink',
            name='icon_class',
            field=models.CharField(default='fab fa-telegram', help_text='Font Awesome 6 icon class, e.g. fab fa-telegram, fab fa-whatsapp, fab fa-youtube', max_length=100),
        ),
    ]
