# Generated by Django 6.0.5 on 2026-05-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description shown to users', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Payment Method',
                'verbose_name_plural': 'Global Payment Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text='Name for a custom method not in the global list', max_length=100)),
                ('account_number', models.CharField(help_text="User's account/phone number for this method", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='User can toggle this on/off without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_method', models.ForeignKey(blank=True, help_text='Admin-defined global method (leave blank for custom methods)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_methods', to='payments.globalpaymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Method',
                'verbose_name_plural': 'User Payment Methods',
                'ordering': ['global_method__name', 'custom_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'global_method'), name='unique_user_global_method'), models.UniqueConstraint(condition=models.Q(('custom_name', ''), _negated=True), fields=('user', 'custom_name'), name='unique_user_custom_name')],
            },
        ),
    ]
