# Generated by Django 6.0.5 on 2026-05-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_custom_method_support'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpaymentmethod',
            name='unique_user_global_method',
        ),
    ]
