# Generated by Django 6.0.5 on 2026-05-09 06:20

import coins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=coins.models.generate_order_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coin_amount',
            field=models.PositiveIntegerField(help_text='Amount in raw coins (e.g., 5000)'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='user_number',
            field=models.CharField(help_text="User's own account number", max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentnumber',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Maximum coin amount in raw coins (e.g., 5000 = 5K)'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='min_amount',
            field=models.PositiveIntegerField(help_text='Minimum coin amount in raw coins (e.g., 1000 = 1K)'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='price_per_k',
            field=models.DecimalField(decimal_places=2, help_text='Price per 1000 coins (1K)', max_digits=10),
        ),
    ]
