# Generated by Django 6.0.5 on 2026-05-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_order_order_id_alter_order_coin_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_sender_token', models.BooleanField(default=False, help_text='If enabled, customers must provide a sender username or coupon token when placing an order.')),
                ('sender_token_label', models.CharField(default='Sender Username / Coupon Token', help_text='Label shown to the customer on the order form.', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='sender_token',
            field=models.CharField(blank=True, help_text='Sender username or coupon token provided by the customer (required when enabled in Site Settings)', max_length=200),
        ),
    ]
