# Generated by Django 6.0.5 on 2026-05-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_sitesettings_order_sender_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AddField(
            model_name='coin',
            name='require_sender_token',
            field=models.BooleanField(default=False, help_text='When ON, customers must provide a sender username or coupon code to place an order for this coin.', verbose_name='Require sender username / coupon code'),
        ),
        migrations.AddField(
            model_name='coin',
            name='sender_token_label',
            field=models.CharField(default='Sender Username / Coupon Code', help_text="Label shown to the customer on the order form (e.g. 'Referral Code', 'Coupon Token').", max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_token',
            field=models.CharField(blank=True, help_text='Sender username or coupon code submitted by the customer', max_length=200),
        ),
    ]
