# Generated by Django 6.0.5 on 2026-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_delete_sitesettings_coin_require_sender_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='screenshot_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
