# Generated by Django 6.0.5 on 2026-05-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_order_screenshot_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentNumber',
        ),
    ]
