# Generated by Django 6.0.5 on 2026-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='coin',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
    ]
