# Generated by Django 6.0.5 on 2026-05-18 12:09

import django.db.models.deletion
from django.db import migrations, models


def merge_all_payment_methods(apps, schema_editor):
    """Merge payment methods from both coins and instagram_work into GlobalPaymentMethod,
    deduplicating by name (coins entries take priority for ID assignment)."""
    GlobalPaymentMethod = apps.get_model('payments', 'GlobalPaymentMethod')

    CoinPM = apps.get_model('coins', 'PaymentMethod')
    for old in CoinPM.objects.all():
        GlobalPaymentMethod.objects.get_or_create(
            name=old.name,
            defaults={'is_active': old.is_active},
        )

    try:
        IGPM = apps.get_model('instagram_work', 'PaymentMethod')
        for old in IGPM.objects.all():
            GlobalPaymentMethod.objects.get_or_create(
                name=old.name,
                defaults={'is_active': old.is_active},
            )
    except LookupError:
        pass


def link_order_payment_fks(apps, schema_editor):
    """Update OrderPayment.payment_method FK to point to new GlobalPaymentMethod."""
    OrderPayment = apps.get_model('coins', 'OrderPayment')
    GlobalPaymentMethod = apps.get_model('payments', 'GlobalPaymentMethod')
    CoinPM = apps.get_model('coins', 'PaymentMethod')

    name_to_global = {g.name: g for g in GlobalPaymentMethod.objects.all()}
    old_to_new = {}
    for old in CoinPM.objects.all():
        gpm = name_to_global.get(old.name)
        if gpm:
            old_to_new[old.pk] = gpm.pk

    for op in OrderPayment.objects.all():
        new_id = old_to_new.get(op.payment_method_id)
        if new_id:
            op.payment_method_id = new_id
            op.save(update_fields=['payment_method_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0009_add_performance_indexes'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop old FK so data can be migrated safely
                migrations.RunSQL(
                    sql='ALTER TABLE coins_orderpayment DROP CONSTRAINT IF EXISTS coins_orderpayment_payment_method_id_1ec06641_fk_coins_pay',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Merge both tables into GlobalPaymentMethod
                migrations.RunPython(merge_all_payment_methods, migrations.RunPython.noop),
                # Update OrderPayment FKs to new GlobalPaymentMethod IDs
                migrations.RunPython(link_order_payment_fks, migrations.RunPython.noop),
                # Add new FK constraint
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE coins_orderpayment '
                        'ADD CONSTRAINT coins_orderpayment_payment_method_fk_payments '
                        'FOREIGN KEY (payment_method_id) REFERENCES payments_globalpaymentmethod(id) '
                        'DEFERRABLE INITIALLY DEFERRED'
                    ),
                    reverse_sql=(
                        'ALTER TABLE coins_orderpayment '
                        'DROP CONSTRAINT IF EXISTS coins_orderpayment_payment_method_fk_payments'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='orderpayment',
                    name='payment_method',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='payments.globalpaymentmethod',
                    ),
                ),
                migrations.AddField(
                    model_name='orderpayment',
                    name='is_global',
                    field=models.BooleanField(default=True),
                ),
                migrations.DeleteModel(
                    name='PaymentMethod',
                ),
            ],
        ),
    ]
