# Generated by Django 6.0.5 on 2026-05-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='ban_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
