# Generated by Django 6.0.5 on 2026-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0002_add_ban_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(default='Welcome to MetaIncomeHub! 🚀\n\nEarn money by completing simple tasks and submitting your work.', help_text='Message shown when a user sends /start to the bot (Markdown supported).')),
                ('button_text', models.CharField(default='Open MetaIncomeHub', help_text='Label for the button that opens the Mini App.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Start Message',
                'verbose_name_plural': 'Bot Start Message',
            },
        ),
    ]
