# Generated by Django 6.0.5 on 2026-05-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0003_add_bot_start_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
